# pip-hash
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/pip-hash.1.gz
complete -c pip-hash -s a -l algorithm -d 'The hash algorithm to use: one of sha256, sha384, sha512 '

