# pip-search
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/pip-search.1.gz
complete -c pip-search -s i -l index -d 'Base URL of Python Package Index (default \\%https://pypi. org/pypi) '

