# pip-cache
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/pip-cache.1.gz
complete -c pip-cache -l format -d 'Select the output format among: human (default) or abspath '

